name: Multi-App Build, Scan, and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [red-app, blue-app, green-app]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.app }}:latest ./${{ matrix.app }}

    - name: Install Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.app }}:latest
        exit-code: 0  # Change to 1 if you want to break build on vulnerabilities
        severity: CRITICAL,HIGH

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.app }}:latest
